# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f58f644900a24b2f6c596728e81b0e7a0610b0e6eccf57b625d911286971637b3dba61abc34bd816ae97f1549042e1dc26c2324380f6899342183076b293c4ae

test:
  secret_key_base: 69a7ce7bb300bdf695197484360ed9571076c39ff282ffff266c5f279b1fb4f983a22825576e61587579b54f42381c2ac7c51a0acd99221017c9bc20cb813d85

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
